language: node_js
node_js: "node"

before_script:
  - npm install qxcompiler 
  - pushd node_modules/qxcompiler
  - npm update qooxdoo-sdk
  - popd 

script:
  - node_modules/qxcompiler/qx compile --target=build -v
  

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: build-output
  on:
    branch: master
